// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqqmladcgmpjbcsklfab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxcW1sYWRjZ21wamJjc2tsZmFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNDgwMDQsImV4cCI6MjA1NzcyNDAwNH0.De60Wxh1ynA7BSFf0SONeNYzjZ2dYHogOeVl1-JJq8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);